CREATE TABLE ORDERS(
    ORDER_ID    SERIAL PRIMARY KEY,
    CUSTOMER_ID INT
);

CREATE TABLE ORDER_LINES(
    ORDER_ID    INT NOT NULL,
    PRODUCT_ID  INT NOT NULL,
    BRAND       VARCHAR,
    TYPE        VARCHAR,
    QUANTITY    INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT FK_ORDERS FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);